language: python
python: 2.7
sudo: required
dist: trusty
env:
- WHEELHOUSE=$HOME/.cache/wheelhouse PIP_FIND_LINKS=file://$WHEELHOUSE PIP_WHEEL_DIR=$WHEELHOUSE
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.cache/wheelhouse"
  - slyd/node_modules
  - slyd/bower_components

before_install:
- export SPLASH_PYTHON_VERSION=venv
- curl -L -o splash.tar.gz 'https://github.com/scrapinghub/splash/archive/master.tar.gz'
- tar -xvf splash.tar.gz --keep-newer-files
- mv splash-* splash
- cd splash/
- export SPLASH_PYTHON_VERSION=venv
# install common packages
- sudo bash -x dockerfiles/splash/provision.sh prepare_install
- sudo apt-get install -y zlib1g-dev libssl-dev python-openssl

# install QT5
- sudo -E bash -x dockerfiles/splash/provision.sh install_builddeps
- sudo -E bash -x dockerfiles/splash/provision.sh install_deps

# instal PyQT5
- sudo -E bash -x dockerfiles/splash/provision.sh install_pyqt5

# install Python packages
- source ${VIRTUAL_ENV}/bin/activate
- bash -x dockerfiles/splash/provision.sh install_python_deps
- cd ..

install:
- source ${VIRTUAL_ENV}/bin/activate
- sudo ./provision.sh install_deps install_splash install_python_deps
- cd slyd
- npm install -g bower
- npm install
- bower install
- cd ..

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- source ${VIRTUAL_ENV}/bin/activate
- export PYTHONPATH=`pwd`/slybot:`pwd`/slyd
- cd slyd
- pip install qt5reactor-fork
- python -c 'import sys; print sys.path'
- python -c 'import splash'
- python -c 'import qt5reactor'
- python tests/testserver/server.py 2>&1 | grep -v 'HTTP/1.1" 200' &
- cd ..
- sleep 3 # give xvfb some time to start
script:
- cd ./slybot
- nosetests --with-doctest
- cd ../slyd
- npm test
- nosetests --with-doctest
- cd ../
before_deploy:
- cd ./slybot
- pip install twine
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: S5hZT2YBncUSkPTyR5RUQnACfTsW2ZtpHeQucIamKWN+xkE8KK9O0cWUMuKQ0q3U5ShFkZdhO4PnBjvtP54Dq9IogJAudkDJCylctf4qGoIlWu01mAoJzcUfrS5KW+VolF/opBJObwG38EIOOsVy9UYq7DeQcryAAG1RuMjONAk=
  on:
    all_branches: true
    tags: true
    repo: scrapinghub/portia
    condition: "$TRAVIS_TAG =~ ^slybot-[0-9][.][0-9]*"
